language: python

python:
  - 3.5.2

addons:
  - postgresql: "9.5.7"

before_install:
  - export DJ_DEBUG=False
  - export DABATASE_URL=postgres://postgres@localhost/travisdb

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres
  - python manage.py migrate --noinput

env:
  - DJANGO=1.10.7

script: python manage.py test --keepdb
