version: '3'

services:
  db:
    restart: always
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    restart: always
    image: drfaustusfade/testgirls:latest
    command: >
              bash -c "python3 manage.py makemigrations &&
                       python3 manage.py migrate &&
                       gunicorn mysite.wsgi -b 0.0.0.0:8000"
                      # python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - pgdata:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
    driver: cloudstor:aws
    driver_opts: 
      size: 1
